theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  posts:
    index:
      layout: grid
  persons:
    index:
      layout: grid
