theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  posts:
    index:
      show_categories: true
      truncate_description: 200 # Set to 0 to disable truncate
      layout: grid
  pages:
    index:
      truncate_description: 200 # Set to 0 to disable truncate
  persons:
    index:
      layout: grid